from datetime import datetime

def generate_vulnerability_report(vulnerability, system_info, mitigation_steps):
    """Generate an HTML report for a vulnerability"""
    report_template = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Vulnerability Assessment Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #333; }
            .container { max-width: 1000px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
            h2 { color: #2980b9; margin-top: 20px; }
            .severity-high { background-color: #e74c3c; color: white; padding: 5px 10px; border-radius: 3px; }
            .severity-medium { background-color: #f39c12; color: white; padding: 5px 10px; border-radius: 3px; }
            .severity-low { background-color: #3498db; color: white; padding: 5px 10px; border-radius: 3px; }
            .severity-na { background-color: #95a5a6; color: white; padding: 5px 10px; border-radius: 3px; }
            .section { margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-radius: 5px; }
            code { background: #f4f6f8; padding: 2px 5px; border-radius: 3px; font-family: monospace; }
            .mitigation { background: #eafaf1; padding: 15px; border-left: 5px solid #2ecc71; }
            .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #7f8c8d; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Vulnerability Assessment Report</h1>
            
            <div class="section">
                <h2>Vulnerability Details</h2>
                <p><strong>CVE ID:</strong> {{cve_id}}</p>
                <p><strong>Severity:</strong> <span class="severity-{{severity_class}}">{{severity}}</span></p>
                <p><strong>Base Score:</strong> {{base_score}}</p>
                <p><strong>Published:</strong> {{published_date}}</p>
                <p><strong>Description:</strong> {{description}}</p>
            </div>
            
            <div class="section">
                <h2>System Information</h2>
                <p><strong>Operating System:</strong> {{os_name}} {{os_version}} ({{os_arch}})</p>
                <p><strong>Distribution:</strong> {{os_dist}}</p>
                <p><strong>Processor:</strong> {{processor}}</p>
                <p><strong>Assessment Date:</strong> {{assessment_date}}</p>
            </div>
            
            <div class="section mitigation">
                <h2>Mitigation Steps</h2>
                {{mitigation_steps}}
            </div>
            
            <div class="footer">
                <p>Generated by OS Vulnerability Assessment Tool on {{generated_date}}</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    # Extract vulnerability details
    cve = vulnerability.get('cve', {})
    cve_id = cve.get('id', 'Unknown')
    description = cve.get('descriptions', [{}])[0].get('value', 'No description available')
    
    # Extract metrics
    metrics = cve.get('metrics', {})
    cvss_data = metrics.get('cvssMetricV31', [{}])[0] if 'cvssMetricV31' in metrics else metrics.get('cvssMetricV2', [{}])[0] if 'cvssMetricV2' in metrics else {}
    
    base_score = cvss_data.get('cvssData', {}).get('baseScore', 'N/A') if cvss_data else 'N/A'
    severity = cvss_data.get('cvssData', {}).get('baseSeverity', 'N/A') if cvss_data else 'N/A'
    
    # Determine severity class for styling
    severity_class = "na"
    if severity == "HIGH" or severity == "CRITICAL":
        severity_class = "high"
    elif severity == "MEDIUM":
        severity_class = "medium"
    elif severity == "LOW":
        severity_class = "low"
    
    # Get published date
    published_date = cve.get('published', 'Unknown')
    
    # Format the mitigation steps from LLM
    formatted_mitigation = mitigation_steps.replace('\n', '<br>')
    
    # Replace template variables
    report = report_template.replace('{{cve_id}}', cve_id)
    report = report.replace('{{severity}}', severity)
    report = report.replace('{{severity_class}}', severity_class)
    report = report.replace('{{base_score}}', str(base_score))
    report = report.replace('{{published_date}}', published_date)
    report = report.replace('{{description}}', description)
    report = report.replace('{{os_name}}', system_info['os']['name'])
    report = report.replace('{{os_version}}', system_info['os']['version'])
    report = report.replace('{{os_arch}}', system_info['os']['architecture'])
    report = report.replace('{{os_dist}}', system_info['os']['distribution'])
    report = report.replace('{{processor}}', system_info['hardware']['processor'])
    report = report.replace('{{assessment_date}}', datetime.now().strftime("%Y-%m-%d"))
    report = report.replace('{{mitigation_steps}}', formatted_mitigation)
    report = report.replace('{{generated_date}}', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    
    return report
